// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDVkNg8voz_Rjv46oXoSvwBfifHLwO7Kiw',
    appId: '1:415196125736:web:ea0acbd1f68a62a240331d',
    messagingSenderId: '415196125736',
    projectId: 'art-shop-sylhet',
    authDomain: 'art-shop-sylhet.firebaseapp.com',
    storageBucket: 'art-shop-sylhet.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBxcj_fNDUnY6ll1gpY0kcTl8BtL93fGSc',
    appId: '1:415196125736:android:f7de437de4468dba40331d',
    messagingSenderId: '415196125736',
    projectId: 'art-shop-sylhet',
    storageBucket: 'art-shop-sylhet.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDnWz04VNBO3rluP3EgYQOBmHVDDru15SI',
    appId: '1:415196125736:ios:885efb98e5bf505140331d',
    messagingSenderId: '415196125736',
    projectId: 'art-shop-sylhet',
    storageBucket: 'art-shop-sylhet.appspot.com',
    iosBundleId: 'com.example.ecommerce',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDnWz04VNBO3rluP3EgYQOBmHVDDru15SI',
    appId: '1:415196125736:ios:885efb98e5bf505140331d',
    messagingSenderId: '415196125736',
    projectId: 'art-shop-sylhet',
    storageBucket: 'art-shop-sylhet.appspot.com',
    iosBundleId: 'com.example.ecommerce',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDVkNg8voz_Rjv46oXoSvwBfifHLwO7Kiw',
    appId: '1:415196125736:web:9b2a4262054d343d40331d',
    messagingSenderId: '415196125736',
    projectId: 'art-shop-sylhet',
    authDomain: 'art-shop-sylhet.firebaseapp.com',
    storageBucket: 'art-shop-sylhet.appspot.com',
  );
}
